### ISSUE TITLE
isLoading never 'true' with upgrade to react 18

### ISSUE THREAD

**Issue by passinator** [authts/react-oidc-context#363]
Been using the library seamlessly up until now so many thanks for this.
Recently I upgraded to react 18 and noticed some weird render behaviour that was previously working fine.

my config is

```
export const oidcConfig = {
  authority: '....',
  client_id: '....',
  redirect_uri: '...',
  post_logout_redirect_uri: '....',
  scope: 'openid profile roles',
  monitorSession: true,
  loadUserInfo: true,
  userStore: new WebStorageStateStore({ store: window.localStorage }),
}
```

I have a button that initiates signinRedirect onClick. In the layout of my app, Im using isLoading from useAuth to render a loading page for the brief seconds before/after redirect takes place where isLoading becomes true. 
After upgrading to react18, isLoading always returns as false or doesn't return anything at all.
This is a react typescript app.

**Comment by pamapa** [comment]
We have recently updated one of our proprietary application to react18. This application works fine. We have code like this:
```
if (auth.isLoading) {
  return <ProgressCentered size={80} />;
}
```

Its hard to say what your problem is. The `isLoading` property is handled like all other properties in this library; via the reducer.ts. You could temporary add there logs are debugging breakpoints, to see whats going on...

**Comment by pamapa** [comment]
i am going to close this issue, unless more details a posted...
